# Generated by Django 2.2.1 on 2019-05-14 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_renting', '0002_car_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(choices=[('requesting', 'requesting'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='requesting', max_length=30)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('booking_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='car_renting.Car')),
            ],
            managers=[
                ('bookings', django.db.models.manager.Manager()),
            ],
        ),
    ]
