# Generated by Django 2.2.1 on 2019-05-14 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_renting', '0005_notification_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='car_renting.Booking'),
        ),
    ]
