# Generated by Django 2.2.1 on 2019-05-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_renting', '0009_auto_20190514_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('requesting', 'requesting'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('canceled', 'canceled')], default='requesting', max_length=30),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='car',
        ),
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.ManyToManyField(related_name='bookings', to='car_renting.Car'),
        ),
    ]
