# Generated by Django 2.2.1 on 2019-05-14 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_renting', '0010_auto_20190514_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='car',
        ),
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='car_renting.Car'),
        ),
    ]
