# Generated by Django 2.2.1 on 2019-05-15 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_renting', '0013_auto_20190515_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
