# Generated by Django 2.2.1 on 2019-05-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_renting', '0016_bookinghistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghistory',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_history', to='car_renting.Car'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications', to='car_renting.Booking'),
        ),
    ]
