# Generated by Django 2.2.1 on 2019-05-19 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_renting', '0018_auto_20190519_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='car_renting.Booking'),
        ),
    ]
