# Generated by Django 2.2.1 on 2019-06-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_renting', '0019_auto_20190519_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=12),
        ),
    ]
