# Generated by Django 2.2.1 on 2019-06-04 14:40

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('car_renting', '0021_paymentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/images/%Y/%m/%d/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='car_renting.Car')),
            ],
            managers=[
                ('images', django.db.models.manager.Manager()),
            ],
        ),
    ]
