# Generated by Django 2.2.1 on 2019-06-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_renting', '0022_carimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarImages',
            new_name='CarImage',
        ),
    ]
