# Generated by Django 2.2.1 on 2019-06-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190604_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='users/user.png', null=True, upload_to='users/images/%Y/%M/%d'),
        ),
    ]
