# Generated by Django 2.2.1 on 2019-05-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190514_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_key',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activation_key_expirity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
